### ISSUE TITLE
Pad silence trimming calculation to prevent cutting off end of audio.

### ISSUE THREAD

**Issue by el-tocino** [MycroftAI/mimic-recording-studio#35]
In certain conditions (English sentences with hard consonants at the end of a sentence?), it appears that MRS may be cutting a bit too aggressively.  I would suggest that a .05s or .1s pad be added to either end of the trimming in order to retain the audio.  

Relevant code:
https://github.com/MycroftAI/mimic-recording-studio/blob/e3e3c8e15544f7e6c7ee2f1f35ea9055908924ce/backend/app/audio.py#L25

**Comment by thorstenMueller** [comment]
Thanks @el-tocino for opening this issue and thanks @krisgesling for the code change.
As i encountered the same problems (_last phonemes of some recordings where cut off_) i applied your patch manually, give it a try and will report feedback.

Do i need to make a docker build after code change or just start by using `docker-compose up`

**Comment by krisgesling** [comment]
Thanks Thorsten - if you give the thumbs up I'll merge it so that we have at least a simple fix. I know others are working on more detailed changes that we can still consider but mostly I don't want to have people getting dud audio in the short term.

`docker-compose up` will rebuild the container if it detects a change you can also use the `--force-recreate` flag to be safe if it's not picking up the changes for some reason.

**Comment by thorstenMueller** [comment]
I've made some quick tests while recording 75 phrases spoken in a normal (_little bit louder_) volume. And in this scenario it seems to work (_no end is cut off_).

![Bildschirmfoto von 2021-06-10 21-10-17](https://user-images.githubusercontent.com/9558265/121583861-16d1f980-ca31-11eb-88fc-b53f487fca9f.png)

But i'll start recording a "whispering" dataset tomorrow so i'll check if the end is not cut off in this scenario. If this works well too, i'll give me thumbs up :-).

**Comment by thorstenMueller** [comment]
I've recorded 300 whispering phrases and listened to them. No phrases has been cutted off :smile: . Tested with default value of 0.3s. 
So here's my thumb up :+1:

**Comment by krisgesling** [comment]
Great, thanks for testing that!

Merging now.
