### ISSUE TITLE
Replay continues after next page

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mimic-recording-studio#5]
If I begin a replay, then click the arrow -> key or Next button to accept it, the replay continues.  I expected the replay to halt.

**Comment by Ruthvicp** [comment]
Made the below UI improvements [here](https://github.com/MycroftAI/mimic-recording-studio/commit/49e1c7746f65b313b47b3b4d92dbe369a6a8e46b)
1. Disable review button when an audio plays
2. Disable next button when an audio plays
3. Avoid jumping to next prompt when a user clicks arrow -> key during replay
