### ISSUE TITLE
Replay is available before recording

### ISSUE THREAD

**Issue by penrods** [MycroftAI/mimic-recording-studio#6]
The Replay button and the text hint suggest [R] is available before you have recorded a phrase.  I'd only say "Spacebar to start recording" and dim the Replay button until a recording exists.

**Comment by Ruthvicp** [comment]
Fixed it [here](https://github.com/MycroftAI/mimic-recording-studio/commit/6ddf000b6c214ed1c7b779a13fb25967d0cf8bd3). Please try and let me know.
