### ISSUE TITLE
Missing requirments.txt

### ISSUE THREAD

**Issue by kingpinzs** [MycroftAI/mimic-recording-studio#62]
**Describe the bug**
the frontend directory is missing the requirements.txt

**To Reproduce**
1. run start-windows.bat

**Expected behavior**
Runs without the error missing requirements.txt

**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: [e.g. Raspberry Pi, Mark 1, desktop]
 - OS: [e.g. Ubuntu, Picroft]
 - Mycroft-core version: [e.g. 20.08]
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**

Please think carefully about whether you have modified anything in Mycroft's code or configuration files.  If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

**Comment by krisgesling** [comment]
Hi there, thanks for logging some bug reports!

If I'm not mistaken, the backend is a Python Flask app which is why it has a `requirements.txt` file. Where as the frontend is  a Javascript React app so its dependencies are defined in the [`package.json` file](https://github.com/MycroftAI/mimic-recording-studio/blob/master/frontend/package.json).

Let me know if I've missed something.

**Comment by krisgesling** [comment]
Interesting - I just saw that `start-windows.bat` tries to install python dependencies for the frontend - that will never work...

I don't have a Windows machine to test with but can you delete [line 81](https://github.com/MycroftAI/mimic-recording-studio/blob/e3e3c8e15544f7e6c7ee2f1f35ea9055908924ce/start-windows.bat#L81) and try again?
