### ISSUE TITLE
Unhandled Rejection (TypeError): Failed to fetch

### ISSUE THREAD

**Issue by ivaxsirc** [MycroftAI/mimic-recording-studio#80]
When enter to localhost:3000 in windows 10 with chrome, appears  
     return fetch(apiRoot + `api/user/?uuid=${uuid}`, {
I show a screenshot, any solution? Thanks
![image](https://user-images.githubusercontent.com/48472866/155840764-0eafe3cb-317f-481a-bce1-125aba7b1813.png)

**Comment by ivaxsirc** [comment]
I answer to myself the problem was backend, you must be opened backend and frontend, now works perfect

**Comment by krisgesling** [comment]
Thanks for updating this - I'm sure it will help someone else in the future who's seeing the same thing :)
