### ISSUE TITLE
Music recording 

### ISSUE THREAD

**Issue by 10baytop** [MycroftAI/mimic-recording-studio#99]
**Describe the bug**

**To Reproduce**
4. See error '....'

**Expected behavior**

**Log files**
If possible, add log files from `/var/log/mycroft/` to help explain your problem.

You may also include screenshots, however screenshots of log files are often difficult to read and parse. 

If you are running Mycroft, the [Support Skill](https://github.com/MycroftAI/skill-support) helps to automate gathering this information. Simply say "Create a support ticket" and the Skill will put together a support package and email it to you.

**Environment (please complete the following information):**
 - Device type: [e.g. Raspberry Pi, Mark 1, desktop]
 - OS: [e.g. Ubuntu, Picroft]
 - Mycroft-core version: [e.g. 20.08]
 - Other versions: [e.g. Adapt v0.3.7]

**Additional context**

Please think carefully about whether you have modified anything in Mycroft's code or configuration files.  If so, can you reproduce this on a clean installation of Mycroft? Many "bugs" turn out to be non-standard configuration errors.

**Comment by krisgesling** [comment]
Hi there, there's nothing here except the default text so I'm assuming your a bot trying to look legitimate by posting in other projects.

If not, please feel free to re-open the ticket with some more detail.
